# Generated by Django 4.1 on 2022-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employees_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Staffs',
        ),
    ]
