# Generated by Django 4.1 on 2022-08-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_employees_staffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
