# Generated by Django 4.1 on 2022-08-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
