# Generated by Django 4.1 on 2022-08-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employees_delete_positions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
