# Generated by Django 4.1 on 2022-08-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
