# Generated by Django 4.1 on 2022-08-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_employee_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
