# Generated by Django 4.1 on 2022-08-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_positions_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
